apiVersion: v1
kind: Service
metadata:
  name: wordpress-banco
  namespace: devops
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-banco
  type: ClusterIP
status:
  loadBalancer: {}
