apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    field.cattle.io/targetWorkloadIds: '[''devops/wordpress-banco'']'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2021-03-15T23:42:39Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"6ecdae4d-4dc7-4a7b-bffe-3f962adf721a"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3306,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2021-03-15T23:42:40Z"
  name: wordpress-banco
  namespace: devops
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: wordpress-banco
    uid: 6ecdae4d-4dc7-4a7b-bffe-3f962adf721a
  resourceVersion: "14971"
  selfLink: /api/v1/namespaces/devops/services/wordpress-banco
  uid: b12f37f0-4b95-44ef-8928-4a8437eb362e
spec:
  clusterIP: 10.76.5.191
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-banco
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
