apiVersion: v1
kind: Service
metadata:
  name: wordpress-site
  namespace: devops
spec:
  ports:
  - name: wordpress-lb
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-site
  type: ClusterIP
status:
  loadBalancer: {}
