apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: wordpress-deploy-banco
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: storage-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: storage-mysql
        persistentVolumeClaim:
          claimName: storage-mysql
