apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-banco
  namespace: devops
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-banco
  replicas: 1
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-banco
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql_password
              name: mysql-secrets
        image: mysql:5.6
        imagePullPolicy: Always
        name: wordpress-banco
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: storage-mysql
      volumes:
      - name: storage-mysql
        persistentVolumeClaim:
          claimName: storage-mysql
