apiVersion: apps/v1
kind: Deployment
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: wp-rancher
    meta.helm.sh/release-namespace: devops
metadata:
  name: nginx
  namespace: devops
spec:
  selector:
    matchLabels:
        app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
