apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
