apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: wordpress-deploy-site
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-service-banco
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql_password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: storage-site
          mountPath: /var/www/html
      volumes:
      - name: storage-site
        persistentVolumeClaim:
          claimName: storage-site
