apiVersion: v1
kind: Service
metadata:
  name: wordpress-site-loadbalancer
  namespace: devops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: wordpress-lb
    nodePort: 32039
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-site
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.222.8.133
