apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-banco
  labels:
    app: wordpress
    tier: backend
spec:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    tier: backend
  type: ClusterIP
