apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: wordpress-service-banco
  labels:
    app: wordpress
    tier: backend
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
  selector:
    app: wordpress
    tier: backend
  type: ClusterIP
