apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    field.cattle.io/publicEndpoints: '[{"addresses":["35.222.8.133"],"port":80,"protocol":"TCP","serviceName":"devops:wordpress-site-loadbalancer","allNodes":false}]'
    field.cattle.io/targetWorkloadIds: '[''devops/wordpress-site'']'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2021-03-15T23:46:37Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5402cdc2-9acc-49b3-984d-e77f3b69b6b9"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2021-03-15T23:46:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-15T23:47:07Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-03-15T23:47:07Z"
  name: wordpress-site-loadbalancer
  namespace: devops
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: wordpress-site
    uid: 5402cdc2-9acc-49b3-984d-e77f3b69b6b9
  resourceVersion: "16854"
  selfLink: /api/v1/namespaces/devops/services/wordpress-site-loadbalancer
  uid: e4da9eaa-9b1e-48f1-b4e6-919eb8b7972e
spec:
  clusterIP: 10.76.6.13
  externalTrafficPolicy: Cluster
  ports:
  - name: wordpress-lb
    nodePort: 32039
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-devops-wordpress-site
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.222.8.133
