apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: wordpress-service-lb
  labels:
    app: wordpress
    tier: frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: wordpress-lb
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.70.150.201
